# Simulating discrete random variables

# X -> Random variable, Y = F(X)
# F(x) = P(X <= x)
# P(Y <= y) = P(F(X) <= y)
# = P(X <= F^-1(y)), this is IFF F is invertible (this would also mean that 0 <= y <= 1)
# = F(F^-1(y)) = y
# Y ~ Uniform(0, 1)

set.seed(2021)
runif(10)
set.seed(2021)
runif(10)
runif(10)
# R can generate random numbers from random number tables, and you can do so by using runif(x), which generates a sample of x elements from Uniform(0, 1). Setting a seed will let R know a starting point, and since the algorithm is not actually "random", the results obtained from runif will not change. However, after continuing to run runif after setting the seed, we'll start seeing new numbers being generated by the PRNG formula used by R.
# if we don't set a seed, then R will choose a seed by itself (not elaborated on by Siva)

# from now on we'll assume we can generate a random number n in u ~ Uniform(0, 1)
# Generating Bernoulli from Uniform
# X ~ Bernoulli(p), 0 <= p <= 1
# => Range(X) = { 0, 1 }, P(X = 1) = p
# Step 1: Generate u ~ Uniform(0, 1) using R
# Step 2: Define X := 1 if u < p but 0 if u >= p
# P(X = 1) = P(u < p) = p, P(X = 0) = P(u >= p) = (1 - p)

# Generating Binomial from Bernoulli
# X ~ binomial(n, p) <--> X = Σ X_i [ i goes from 1 to n ], where X_i ~ Bernoulli(p) { independent }

# Step 1: Regenerate u_1, u_2, ..., u_n "independent" Uniform(0, 1) samples
# Step 2: X = # {i : 1 <= i <= n & u_i < p }

# Generate samples from Discrete distributions using Uniform variables
# (Ω, , P) -> Probability space
# X: Ω -> S (S is a countable set)
# Range(X) = S
# P(X = x_i) = p_i
# 0 <= p_i <= 1 & Σ p_i = 1
# Step 1: Generate u = Uniform(0, 1) from R
# Step 2: X = x_1, if u < p1, & x_k, if Σ p_i {i from 1 to (k-1)} < u < Σ p_i {i from 1 to k}

# Copy-pasted Siva's weekly R code from "#weekrcode" channel in Slack

# Histogram
## First specifies a sequence of points called breaks (it is an art)
## The breaks separate the stuff into bins and the bins are used to display the data (class frequency is represented by height and area under graph is proportional to corresponding class if ranges are unequal)
library(tidyverse)
ggplot(data = mpg,  mapping = aes(x = cty)) + geom_histogram() # This generates a histogram, but it is using bins = 30 (i.e, binwidth = 1, for now), but better values can be taken using binwidth
ggplot(data = mpg,  mapping = aes(x = cty)) + geom_histogram(binwidth = 3) # So the lower value of binwidth -> finer histograms and higher values -> more clumpy / rough histograms
ggplot(data = mpg,  mapping = aes(x = cty)) + geom_histogram(bins = 10) # You can also set the total number of bins in the histogram and make R set binwidth accordingly

library(viridis)
ggplot(data = mpg,  mapping = aes(x = cty,fill=class)) +
  geom_histogram() +
  scale_fill_viridis(discrete = TRUE) # Makes the same histogram as before BUT adds colors wrt the variable class, we use viridis to simply add some colouring to the plot
# Note that scale_fill_viridis(discrete = TRUE) is equivalent to scale_fill_viridis_d()

ggplot(data = mpg,  mapping = aes(x = cty,fill=class)) + 
  geom_histogram(binwidth = 5) +
  scale_fill_viridis(discrete = TRUE) # histogram using binwidth 5 and coloured because yes

# R: Categorical Data - Factors and Levels
## Ignored typically but its very useful in graph work
## Categorical variables: Qualitative variables, those which cannot be meaningfully expressed in numbers
## R deals with them through use of "factors", and factors are useful in Statistical modelling and plotting data
## Packages: tidyverse-dplyr, tidyr, forcats, readr help in dealing with factors
## Apparently it can be a very frustrating topic? 🤨
## factor(.), converts data into factors, factors are variables that can take any value but you can take a limited number of values
## factors are useful because they can be used to split the data into plottable chunks which makes it easier to graph, plot and analyse 

xc = c("June", "July", "August", "September", "August", "July", "July", "August")
factorxc = factor(xc) # Stores the vectors as integers, but correspond to a character string for display, and assign levels (done by default, as those given by as.character(.) )
# Levels are the unique set of values which can be taken by as.character(.)

xn = c(1, 2, 2, 3, 1, 2, 3, 3, 1, 2, 3, 3, 1)
factorxn = factor(xn)
factorxn

## What's the advantage of using factors?
mean(xn) # Gives me the mean of xn vector
mean(factorxn) # Gives NA because the argument is not numeric, therefore factorxn is a categorical variable, and all elements are interpreted as characters
mean(as.numeric(levels(factorxn)[factorxn])) # Uses levels function & converts factorxn back to the original numeric values

table(factorxc) # Displays the following:
### factorxc
### August      July      June September 
### 3         3         1         1

months = factor(xc, levels = c("Garbage", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"), ordered = TRUE)
months # Adds a bunch of levels manually to the factor (you get to specify the levels), and also sets an order to the levels which is set by the user
# By default the levels are ordered randomly, or unordered
# When factor is created, all its levels are stored with the factor
months[3] < months[4] # Because level of entry 4 is higher than level of entry 3 apparently
table(months) # Displays the number of entries in the factor for each level (all of them), maintains ordering

table(factor(months)) # Displays the number of entries in the factor for each level (for which you have a non-zero number of elements), maintains ordering

x = round(1000*runif(10))
x # Generates 10 pseudo-random 3-digit numbers

# cut(numeric variable, breaks) converts a numeric variable into factors where you specify the number of breaks (that is the number of levels you basically want)
xfactor= cut(x,4)
xfactor
table(xfactor) # Exercise: check how determines the levels

## Exercise
cut(x, 3, labels = c("A", "B", "C"))

## Using pretty cut
xpfactor= cut(x,pretty(x,4))
xpfactor
table(xpfactor)

## Using cut via quantile
xqfactor= cut(x,quantile(x, probs=seq(0,1,0.25))) # Produces factors via percentiles
table(xqfactor)

## EXERCISE: Generate a cut command in which the levels have an equal number of people

x = round(1000*runif(10))
x
xfactor= cut(x,4)
xfactor
table(xfactor)

# The vector 'everyday' contains every day in the year 2021
everyday = seq(from=as.Date('2021-1-1'),
               to=as.Date('2021-12-31'), by='day')
cmonth = format(everyday,'%b') # vector containing the months in the calendar
head(cmonth,3) # Give 3 entries of the vector c month
df= as.data.frame(table(cmonth))
names(df)=c("Month", "Freq")
df # The order of the months is not the same as the calendar we follow

# We are trying to order the levels as the calendar months
everyday = seq(from=as.Date('2021-1-1'),
               to=as.Date('2021-12-31'), by='day')
cmonth = format(everyday,'%b')
months = factor(cmonth,levels=unique(cmonth),ordered=TRUE) # unique(cmonth) returns a vector of elements in the original vector, just that the duplicates are removed
head(months,3)
df2= as.data.frame(table(months))
names(df2)= c("Month", "Freq")
df2

# IMPORTING VALUES FROM CSV into R
## Need to set working directory as the current folder however
decdf = read.csv(file="./KarnatakaGovtCovidData_SivaThirdClass.csv", header = TRUE) # I saved the file under this name
head(decdf, 2)

decdf$Month = months(as.Date(decdf$MB.Date))
data = as.data.frame(table(decdf$Month))
names(data) = c("Month", "val")
data # Dataset containing Month vs val data from the original dataset


decdf= read.csv(file="./Master.csv", header=TRUE)

head(decdf,2)

names(decdf) = c("Sno","District","Pid","Age","Sex",
                 "Description","Symptoms","CMB",
                 "DOA","DOD","MB.Date","Notes")
head(decdf,2)

decdf= read.csv(file="./Master.csv", header=TRUE)
decdf$Month= months(as.Date(decdf$MB.Date))
data = as.data.frame(table(decdf$Month))
names(data) = c("Month", "val")
data


library(tidyverse)
ggplot(data=data, aes(x=Month, y=val,  fill=Month)) +
  geom_bar(stat="identity", width=.4) +
  coord_flip() +
  scale_fill_viridis_d()+
  xlab("") +
  theme_bw()
decdf= read.csv(file="./Master.csv", header=TRUE)
decdf$Month= months(as.Date(decdf$MB.Date))
data = as.data.frame(table(decdf$Month))
names(data) = c("Month", "val")


library(tidyverse)
data  = arrange(data, val)
ggplot(data=data, aes(x=Month, y=val,  fill=Month)) +
  geom_bar(stat="identity", width=.4) +
  scale_fill_viridis_d()+
  coord_flip() +
  xlab("") +
  theme_bw()

decdf= read.csv(file="./Master.csv", header=TRUE)
decdf$Month= months(as.Date(decdf$MB.Date))
data = as.data.frame(table(decdf$Month))
names(data) = c("Month", "val")

library(tidyverse)
data  = arrange(data, val)
data$Month= factor(data$Month, levels=data$Month)
ggplot(data=data, aes(x=Month, y=val, fill=Month)) +
  geom_bar(stat="identity", width=.4) +
  coord_flip() +
  scale_fill_viridis_d()+
  xlab("") +
  theme_bw()

decdf= read.csv(file="./Master.csv", header=TRUE)
names(decdf) = c("Sno","District","Pid","Age","Sex", "Description","Symptoms",
                 "CMB", "DOA","DOD","MB.Date","Notes")
decdf$Month= months(as.Date(decdf$MB.Date))


ggplot(decdf, aes(x = fct_infreq(Month), fill=cut(Age,pretty(Age,4)))) +labs(fill='Age')+
  geom_bar(stat="count", width=.4) + scale_fill_viridis_d()+
  coord_flip()+ theme_bw() +ggtitle("Deceased Month Count- Age Stacked")+ ylab("Count of Deceased") + 
  xlab("Month") + theme_bw()+ theme(plot.title = element_text( color="#e95462",size=14, face="bold",hjust = 0.5))+ 
  theme(axis.title.x = element_text( color="#e95462", size=14, vjust = 0.5,face="bold"), 
        axis.title.y = element_text(color="#e95462", size=14, face="bold") )

ggplot(decdf, aes(x = fct_infreq(Month), fill=cut(Age,pretty(Age,4)))) +labs(fill='Age')+
  geom_bar(stat="count", width=.4) + scale_fill_viridis_d()+
  coord_flip()+ theme_bw() +ggtitle("Deceased Month Count- Age Stacked")+ ylab("Count of Deceased") + xlab("Month") + theme_bw()+ theme(plot.title = element_text( color="#e95462",size=14, face="bold",hjust = 0.5))+ theme(axis.title.x = element_text( color="#e95462", size=14, vjust = 0.5,face="bold"), axis.title.y = element_text(color="#e95462", size=14, face="bold") )
